version: "3.8"

services:
  mysql-inventory:
    image: mysql:8.0
    container_name: mysql-inventory
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventorydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_inventory_data:/var/lib/mysql

  mysql-order:
    image: mysql:8.0
    container_name: mysql-order
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orderdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - mysql_order_data:/var/lib/mysql

  inventoryservice:
    build: ./inventoryservice
    container_name: inventoryservice
    ports:
      - "9093:9093"
    depends_on:
      - mysql-inventory
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-inventory:3306/inventorydb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

  orderservice:
    build: ./orderservice
    container_name: orderservice
    ports:
      - "9094:9094"
    depends_on:
      - mysql-order
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-order:3306/orderdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

volumes:
  mysql_inventory_data:
  mysql_order_data:
