services:
  mysql-auth:
    image: mysql:8.0
    container_name: mysql-auth
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: auth_db
      MYSQL_USER: authuser
      MYSQL_PASSWORD: authpass
    ports:
      - "33051:3306"
    volumes:
      - mysql_auth_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  mysql-inventory:
    image: mysql:8.0
    container_name: mysql-inventory
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventorydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "33071:3306"
    volumes:
      - mysql_inventory_data:/var/lib/mysql
    command: --bind-address=0.0.0.0 --skip-name-resolve
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  mysql-order:
    image: mysql:8.0
    container_name: mysql-order
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orderdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "33081:3306"
    volumes:
      - mysql_order_data:/var/lib/mysql
    command: --bind-address=0.0.0.0 --skip-name-resolve
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  authservice:
    build: ./authservice
    container_name: authservice-app
    ports:
      - "8081:8081"
    depends_on:
      mysql-auth:
        condition: service_healthy
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-auth:3306/auth_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      JWT_SECRET: mySecretKey123456789012345678901234567890123456789012345678901234567890
      JWT_EXPIRATION: 86400000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 120s

  inventoryservice:
    build: ./inventoryservice
    container_name: inventoryservice
    ports:
      - "9093:9093"
    depends_on:
      mysql-inventory:
        condition: service_healthy
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-inventory:3306/inventorydb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9093/actuator/health"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 120s

  orderservice:
    build: ./orderservice
    container_name: orderservice
    ports:
      - "9094:9094"
    depends_on:
      mysql-order:
        condition: service_healthy
      authservice:
        condition: service_healthy
      inventoryservice:
        condition: service_healthy
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-order:3306/orderdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9094/actuator/health"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 120s

  apigateway:
    build: ./apigateway
    container_name: apigateway
    ports:
      - "8080:8080"
    depends_on:
      authservice:
        condition: service_healthy
      inventoryservice:
        condition: service_healthy
      orderservice:
        condition: service_healthy
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      JWT_EXPIRATION: 86400000
      AUTH_SERVICE_URL: http://authservice:8081
      ORDER_SERVICE_URL: http://orderservice:9094
      INVENTORY_SERVICE_URL: http://inventoryservice:9093
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health", "||", "exit", "1"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 180s

volumes:
  mysql_auth_data:
  mysql_inventory_data:
  mysql_order_data:
