version: "3.8"

services:
  mysql-customer:
    image: mysql:8.0
    container_name: mysql-customer
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: customer_db
      MYSQL_USER: customer_user
      MYSQL_PASSWORD: customer_pass
    ports:
      - "33061:3306"
    volumes:
      - mysql_customer_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "customer_user", "-pcustomer_pass"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  mysql-inventory:
    image: mysql:8.0
    container_name: mysql-inventory
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventorydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "33071:3306"
    volumes:
      - mysql_inventory_data:/var/lib/mysql

  mysql-order:
    image: mysql:8.0
    container_name: mysql-order
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orderdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "33081:3306"
    volumes:
      - mysql_order_data:/var/lib/mysql

  customerservice:
    build: ./customerservice
    container_name: customerservice-app
    ports:
      - "9092:9092"
    environment:
      DB_HOST: mysql-customer
      DB_PORT: 3306
      DB_NAME: customer_db
      DB_USER: customer_user
      DB_PASSWORD: customer_pass
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      mysql-customer:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9092/customers"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  inventoryservice:
    build: ./inventoryservice
    container_name: inventoryservice
    ports:
      - "9093:9093"
    depends_on:
      - mysql-inventory
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-inventory:3306/inventorydb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

  orderservice:
    build: ./orderservice
    container_name: orderservice
    ports:
      - "9094:9094"
    depends_on:
      - mysql-order
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-order:3306/orderdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

volumes:
  mysql_customer_data:
  mysql_inventory_data:
  mysql_order_data:
