apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: order-mysql-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-mysql
  template:
    metadata:
      labels:
        app: order-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: order_db
            - name: MYSQL_USER
              value: order_user
            - name: MYSQL_PASSWORD
              value: order_pass
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: order-mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: order-mysql
spec:
  selector:
    app: order-mysql
  ports:
    - port: 3306
      targetPort: 3306


