apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
  namespace: food-delivery
  labels:
    app: apigateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
      - name: apigateway
        image: lasitha6646/food-delivery-apigateway:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SPRING_PROFILES_ACTIVE
        - name: AUTH_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: AUTH_SERVICE_URL
        - name: ORDER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: ORDER_SERVICE_URL
        - name: FOOD_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: FOOD_SERVICE_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: JWT_SECRET
        - name: JWT_EXPIRATION
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: JWT_EXPIRATION
        - name: CORS_ALLOWED_ORIGINS
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: CORS_ALLOWED_ORIGINS
        - name: CORS_ALLOWED_METHODS
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: CORS_ALLOWED_METHODS
        - name: CORS_ALLOWED_HEADERS
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: CORS_ALLOWED_HEADERS
        - name: CORS_ALLOW_CREDENTIALS
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: CORS_ALLOW_CREDENTIALS
        # Multipart configuration for file uploads
        - name: SPRING_SERVLET_MULTIPART_ENABLED
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SPRING_SERVLET_MULTIPART_ENABLED
        - name: SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE
        - name: SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 180
          periodSeconds: 30
          timeoutSeconds: 15
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: apigateway
  namespace: food-delivery
  labels:
    app: apigateway
spec:
  selector:
    app: apigateway
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer
