apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodservice
  namespace: food-delivery
  labels:
    app: foodservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: foodservice
  template:
    metadata:
      labels:
        app: foodservice
    spec:
      containers:
      - name: foodservice
        image: lasitha6646/food-delivery-foodservice:latest
        ports:
        - containerPort: 9093
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SPRING_PROFILES_ACTIVE
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-food:3306/fooddb"
        - name: SPRING_DATASOURCE_USERNAME
          value: "user"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "password"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 9093
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 15
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 9093
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: foodservice
  namespace: food-delivery
  labels:
    app: foodservice
spec:
  selector:
    app: foodservice
  ports:
  - port: 9093
    targetPort: 9093
  type: ClusterIP
