apiVersion: apps/v1
kind: Deployment
metadata:
  name: customerservice
spec:
  selector:
    matchLabels:
      app: customerservice
  template:
    metadata:
      labels:
        app: customerservice
    spec:
      containers:
        - name: app
          image: customerservice:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_HOST
              value: customer-mysql
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: customer_db
            - name: DB_USER
              value: customer_user
            - name: DB_PASSWORD
              value: customer_pass
            - name: KAFKA_BOOTSTRAP
              value: kafka:9092
          ports:
            - containerPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: customerservice
spec:
  selector:
    app: customerservice
  ports:
    - port: 9092
      targetPort: 9092


