apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderservice
spec:
  selector:
    matchLabels:
      app: orderservice
  template:
    metadata:
      labels:
        app: orderservice
    spec:
      containers:
        - name: app
          image: orderservice:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_URL
              value: jdbc:mysql://order-mysql:3306/order_db
            - name: DB_USER
              value: order_user
            - name: DB_PASSWORD
              value: order_pass
            - name: KAFKA_BOOTSTRAP
              value: kafka:9092
          ports:
            - containerPort: 9091
---
apiVersion: v1
kind: Service
metadata:
  name: orderservice
spec:
  selector:
    app: orderservice
  ports:
    - port: 9091
      targetPort: 9091


