apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurantservice
spec:
  selector:
    matchLabels:
      app: restaurantservice
  template:
    metadata:
      labels:
        app: restaurantservice
    spec:
      containers:
        - name: app
          image: restaurantservice:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_URL
              value: jdbc:mysql://inventory-mysql:3306/inventory_db
            - name: DB_USER
              value: inventory_user
            - name: DB_PASSWORD
              value: inventory_pass
            - name: KAFKA_BOOTSTRAP
              value: kafka:9092
          ports:
            - containerPort: 9093
---
apiVersion: v1
kind: Service
metadata:
  name: restaurantservice
spec:
  selector:
    app: restaurantservice
  ports:
    - port: 9093
      targetPort: 9093


