name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_PREFIX: ${{ github.repository_owner }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - name: authservice
            context: ./Backend/authservice
            dockerfile: ./Backend/authservice/Dockerfile
          - name: restaurantservice
            context: ./Backend/restaurantservice
            dockerfile: ./Backend/restaurantservice/Dockerfile
          - name: orderservice
            context: ./Backend/orderservice
            dockerfile: ./Backend/orderservice/Dockerfile
          - name: apigateway
            context: ./Backend/apigateway
            dockerfile: ./Backend/apigateway/Dockerfile
          - name: frontend
            context: ./frontend
            dockerfile: ./frontend/Dockerfile

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/food-delivery-${{ matrix.service.name }}
        tags: |
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}
          type=schedule,pattern={{date 'YYYYMMDD-HHmmss'}}

    - name: Generate extra tags (version, datetime, sha)
      id: tagger
      run: |
        set -eux
        # Try to get the latest git tag as version, fallback to 'dev'
        VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "dev")
        # UTC datetime
        DATETIME=$(date -u +"%Y%m%d-%H%M%S")
        # Full SHA and short SHA
        FULL_SHA=${GITHUB_SHA}
        SHORT_SHA=${GITHUB_SHA::7}
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
        echo "datetime=${DATETIME}" >> $GITHUB_OUTPUT
        echo "full_sha=${FULL_SHA}" >> $GITHUB_OUTPUT
        echo "short_sha=${SHORT_SHA}" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ${{ matrix.service.context }}
        file: ${{ matrix.service.dockerfile }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ${{ steps.meta.outputs.tags }}
          ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/food-delivery-${{ matrix.service.name }}:${{ steps.tagger.outputs.full_sha }}
          ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/food-delivery-${{ matrix.service.name }}:${{ steps.tagger.outputs.short_sha }}
          ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/food-delivery-${{ matrix.service.name }}:${{ steps.tagger.outputs.version }}
          ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/food-delivery-${{ matrix.service.name }}:build-${{ steps.tagger.outputs.datetime }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64,linux/arm64

