name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_PREFIX: ${{ github.repository_owner }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.tagger.outputs.version }}
      datetime: ${{ steps.tagger.outputs.datetime }}
      full_sha: ${{ steps.tagger.outputs.full_sha }}
      short_sha: ${{ steps.tagger.outputs.short_sha }}
    strategy:
      matrix:
        service:
          - name: authservice
            context: ./Backend/authservice
            dockerfile: ./Backend/authservice/Dockerfile
          - name: foodservice
            context: ./Backend/foodservice
            dockerfile: ./Backend/foodservice/Dockerfile
          - name: orderservice
            context: ./Backend/orderservice
            dockerfile: ./Backend/orderservice/Dockerfile
          - name: apigateway
            context: ./Backend/apigateway
            dockerfile: ./Backend/apigateway/Dockerfile
          - name: frontend
            context: ./frontend
            dockerfile: ./frontend/Dockerfile

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0   
        fetch-tags: true 

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/food-delivery-${{ matrix.service.name }}
        tags: |
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}
          type=schedule,pattern={{date 'YYYYMMDD-HHmmss'}}

    - name: Generate extra tags (version, datetime, sha)
      id: tagger
      run: |
        set -eux
        BASE_VERSION=$(git tag --sort=-v:refname | head -n 1)
        DATE=$(date -u +"%Y%m%d")
        TIME=$(date -u +"%H%M%S")
        DATETIME="${DATE}-${TIME}"
        SHORT_SHA=${GITHUB_SHA::7}

        # Build combined version tag: base version + date
        if [ "$BASE_VERSION" = "dev" ]; then
          FULL_VERSION="dev-${DATETIME}"
        else
          FULL_VERSION="${BASE_VERSION}.${DATETIME}"
        fi

        echo "version=${BASE_VERSION}" >> $GITHUB_OUTPUT
        echo "datetime=${DATETIME}" >> $GITHUB_OUTPUT
        echo "short_sha=${SHORT_SHA}" >> $GITHUB_OUTPUT
        echo "full_version=${FULL_VERSION}" >> $GITHUB_OUTPUT
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ${{ matrix.service.context }}
        file: ${{ matrix.service.dockerfile }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/food-delivery-${{ matrix.service.name }}:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/food-delivery-${{ matrix.service.name }}:${{ steps.tagger.outputs.short_sha }}
          ${{ secrets.DOCKERHUB_USERNAME }}/food-delivery-${{ matrix.service.name }}:${{ steps.tagger.outputs.full_version }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64,linux/arm64
